---
- name: Install Webmin
  hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - software-properties-common
        state: present

    - name: Add Webmin repository key
      apt_key:
        url: http://www.webmin.com/jcameron-key.asc
        state: present

    - name: Add Webmin repository
      apt_repository:
        repo: 'deb http://download.webmin.com/download/repository sarge contrib'
        state: present

    - name: Update apt package list after adding Webmin repository
      apt:
        update_cache: yes

    - name: Install Webmin
      apt:
        name: webmin
        state: present

    - name: Ensure Webmin is started and enabled
      systemd:
        name: webmin
        enabled: yes
        state: started
